apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vYWNjb3VudHMtZGItMi1wb3N0Z3Jlc3FsLmRiLTI6NTQzMi9kYXRlbmJhbms=
  SPRING_DATASOURCE_USERNAME: dG93bmVy
  SPRING_DATASOURCE_PASSWORD: dG93bmVy
  KC_URL: aHR0cHM6Ly9pYW0vYXV0aA==
  KC_CLIENT_ID: dGVzdC1jbGllbnQ=
  KC_CLIENT_SECRET: UHNMQ1FkN3NxbWpSQVFqZHZKbEdaZkV5UVhaSGplTng=
  KC_REALM: dGVzdA==


 
