apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: temp
  name: pod-and-service-creator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create"   , "get"] 
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list","create"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","create"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: temp
  name: pod-and-service-creator-binding
subjects:
  - kind: ServiceAccount
    name: pod-builder-sa
    namespace: temp
roleRef:
  kind: Role
  name: pod-and-service-creator-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: pod-builder-sa-token
  namespace: temp
  annotations:
    kubernetes.io/service-account.name: "pod-builder-sa"
type: kubernetes.io/service-account-token
