version: '3'
services:
  db:
    image: postgres
    container_name: account-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=datenbank
    volumes: 
      - accounts_db:/var/lib/postgresql
  api:
    build: .
    container_name: account-api
    ports: 
      - "8080:8080"

volumes: 
    accounts_db:
       
 
