version: '3'
services:
  db:
    image: postgres
    container_name: account-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=datenbank
  api:
    build:
      context: ./Dockerfile
    container_name: account-api
    ports: 
      - "8080:8080"
 
 
