CREATE USER delete WITH PASSWORD 'delete';

GRANT CONNECT ON DATABASE datenbank TO delete;
GRANT USAGE ON SCHEMA public TO delete;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO delete;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT DELETE ON TABLES TO delete;
