apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-project-api
  labels:
    app: accounts-api
spec: 
    selector:  
      matchLabels:
        app: accounts-api
    template:
      metadata:
       labels:
         app: accounts-api 
      spec:
         containers:
         - name: accounts-api
           # image number four for single table configuration
           image: localhost:5000/accounts-api:4
           ports:
           - containerPort: 8080
           envFrom:
           - configMapRef:
               name: accounts-api-configmap
           readinessProbe:
            httpGet:
             path: "/actuator/health/readiness"
             port: 8080
            periodSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: api-svc-01
spec:
  selector:
    app: accounts-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

