apiVersion: v1
kind: Service
metadata:
  name: api-svc-01
spec:
  type: ExternalName
  externalName: api-svc-01.{{ .Values.primaryNameSpace }}.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: api-svc-02
spec:
  type: ExternalName
  externalName: api-svc-01.temp.svc.cluster.local