apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis
  labels:
    app: da-api
spec: 
    selector:  
      matchLabels:
        app: da-api
    template:
      metadata:
       labels:
         app: da-api
      spec:
         hostUsers: false
         containers:
         - name: da-api
           image: localhost/dataanalysis:1
           env:
            - name: MY_ENV_VAR
              value: "my_value"
           resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
           ports: 
           - containerPort: 8080



