apiVersion: v1
kind: Pod
metadata:
  name: fortio
  labels:
    app: fortio
spec:
  containers:
  - name: fortio
    image: fortio/fortio 
    ports:
    - containerPort: 8080
    command: ["fortio", "server"]
  hostAliases:
    - ip: "192.168.127.2"
      hostnames:
      - "prototype"


