# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

accountsApi: 
  deployment: banking-project-api
  config: accounts-api-configmap
  appName: accounts-api
  readiness:
      method: 'httpGet:'
      path: /actuator/health/readiness
      port: http
      periodSeconds: 5
      initialDelaySeconds: 10
      failureThreshold: 5
  svcName: api-svc-01
  connection:
    port: 8080
    protocol: TCP
  secret: 
    name: spring-secret
    keys: 
     - SPRING_DATASOURCE_URL
     - SPRING_DATASOURCE_USERNAME
     - SPRING_DATASOURCE_PASSWORD
     - KC_URL
     - KC_REALM

   

iam: 
  hostname: iam
  ip: 192.168.56.106


instance: # to be set with external values 

environment:
  registryUrl: docker.registry

db: 
 username: towner
 password: towner
 namespace:  # set with external vars

version:  # set with external vars



