apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: networking
  name: networking-role
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create","get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get"] 
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list","create"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: networking
  name: network-binding
subjects:
  - kind: ServiceAccount
    name: networking-sa
    namespace: networking
roleRef:
  kind: Role
  name: networking-role
  apiGroup: rbac.authorization.k8s.io
