apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset
spec:
  template:
    spec:
      volumes:
      - name: secret-connection-volume
        secret:
         secretName: kill-connections-secret
      containers:
      - name: reset-db
        image: postgres:latest
        command: ["psql","-h", "accounts-db-2-postgresql.db-2", "-U","admin","-d","datenbank","-a","-f","/etc/secret-volume/connections/.secret-file" ]
        env:
         - name: PGPASSWORD
           value: "admin"
        volumeMounts:
        - name: secret-connection-volume
          readOnly: true
          mountPath: "/etc/secret-volume/connections"
      restartPolicy: Never
  backoffLimit: 4