apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset
spec:
  template:
    metadata:
      labels:
        app: cron
    spec:
      volumes:
      - name: secret-connection-volume
        secret:
         secretName: kill-connections-sql
      containers:
      - name: reset-db
        image: postgres:latest
        command: ["psql","-h", "accounts-db-2-postgresql.db-2", "-U","postgres","-d","postgres","-a","-f","/etc/secret-volume/connections/.secret-file" ]
        env:
         - name: PGPASSWORD
           value: "3D8SZZLpOx"
        volumeMounts:
        - name: secret-connection-volume
          readOnly: true
          mountPath: "/etc/secret-volume/connections" 
      restartPolicy: Never
  backoffLimit: 4

  # sources
  # https://kubernetes.io/docs/concepts/configuration/secret/
  # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
  # https://stackoverflow.com/questions/40713573/how-to-run-containers-sequentially-as-a-kubernetes-job
  # https://stackoverflow.com/questions/14486241/postgresql-export-the-schema-of-a-database
  # https://stackoverflow.com/questions/66478086/kubernetes-cronjob-labeling-with-a-network-policy