apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset
spec:
  template:
    metadata:
      labels:
        app: cron
    spec:
      volumes:
        - name: deletion-volume
          secret:
            secretName: delete-tables-sql
        - name: pg-pass 
          secret:
            secretName: pgpassfile
        - name: temp-volume
          emptyDir: {}
      containers:
      - name: fill-db-with-schema
        securityContext:
             capabilities:
               drop:
                 - ALL
             seccompProfile:
               type: RuntimeDefault
             runAsUser: 1000
             procMount: Default
             privileged: false
             allowPrivilegeEscalation: false
             runAsNonRoot: true
        image: postgres:latest
        command:
          - /bin/sh
          - -c
          - |
            cp /etc/pgpassdir/.secret-file /tmp/.pgpassfile
            chmod 600 /tmp/.pgpassfile
            psql -h accounts-db-2-postgresql.db-2 -U towner -d datenbank -a -f /etc/secret-volume/connections/.secret-file
            echo "//////  DATA DELETED ///////////\n"
            sleep 3
            pg_dump --schema-only -h accounts-db-postgresql.db -U transfernew -d datenbank > /tmp/dump.sql
            sleep 2
            cat /tmp/dump.sql
            psql -h accounts-db-2-postgresql.db-2 -d datenbank -U towner < /tmp/dump.sql
        env:
           - name: PGPASSFILE
             value: "/tmp/.pgpassfile"
        volumeMounts:
            - name: deletion-volume
              readOnly: true
              mountPath: "/etc/secret-volume/connections"
            - name: pg-pass
              readOnly: true
              mountPath: "/etc/pgpassdir"
            - name: temp-volume
              mountPath: /tmp
      restartPolicy: Never
  backoffLimit: 1

  # sources
  # https://kubernetes.io/docs/concepts/configuration/secret/
  # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
  # https://stackoverflow.com/questions/40713573/how-to-run-containers-sequentially-as-a-kubernetes-job
  # https://stackoverflow.com/questions/14486241/postgresql-export-the-schema-of-a-database
  # https://stackoverflow.com/questions/66478086/kubernetes-cronjob-labeling-with-a-network-policy
  # https://tableplus.com/blog/2019/09/how-to-use-pgpass-in-postgresql.html
            