apiVersion: v1
kind: Secret
metadata:
  name: delete-tables-sql
data:
  .secret-file: RE8gJCQgREVDTEFSRQogICAgciBSRUNPUkQ7CkJFR0lOCiAgICAtLSBpZiB0aGUgc2NoZW1hIHlvdSBvcGVyYXRlIG9uIGlzIG5vdCAiY3VycmVudCIsIHlvdSB3aWxsIHdhbnQgdG8KICAgIC0tIHJlcGxhY2UgY3VycmVudF9zY2hlbWEoKSBpbiBxdWVyeSB3aXRoICdzY2hlbWF0b2RlbGV0ZXRhYmxlc2Zyb20nCiAgICAtLSAqYW5kKiB1cGRhdGUgdGhlIGdlbmVyYXRlICdEUk9QLi4uJyBhY2NvcmRpbmdseS4KICAgIEZPUiByIElOIChTRUxFQ1QgdGFibGVuYW1lIEZST00gcGdfdGFibGVzIFdIRVJFIHNjaGVtYW5hbWUgPSBjdXJyZW50X3NjaGVtYSgpKSBMT09QCiAgICAgICAgRVhFQ1VURSAnRFJPUCBUQUJMRSBJRiBFWElTVFMgJyB8fCBxdW90ZV9pZGVudChyLnRhYmxlbmFtZSkgfHwgJyBDQVNDQURFJzsKICAgIEVORCBMT09QOwpFTkQgJCQ7