apiVersion: v1
kind: Secret
metadata:
  name: pgpassfile
data:
  .secret-file: YWNjb3VudHMtZGItcG9zdGdyZXNxbC5kYjo1NDMyOmRhdGVuYmFuazp0cmFuc2Zlcm5ldzp0cmFuc2ZlcgphY2NvdW50cy1kYi0yLXBvc3RncmVzcWwuZGItMjo1NDMyOmRhdGVuYmFuazphZG1pbjphZG1pbg==