{{ $root := .Values.accountsApi }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.config }}
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-{{ .Values.db.namespace }}-postgresql.{{ .Values.db.namespace }}:5432/datenbank
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.db.password }}