{{ $secretName := .Values.accountsApi.secret.name }}
{{ $root := .Values.accountsApi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.deployment}}
  labels:
    app: {{ $root.appName }}
spec: 
    selector:  
      matchLabels:
        app: {{ $root.appName }}
    template:
      metadata:
       labels:
         app: {{ $root.appName }}
      spec:
         containers:
         - name: {{ $root.appName }}
           image: '{{ .Values.environment.registryUrl }}/{{ $root.appName }}:{{ .Values.version }}'
           ports:
           - containerPort: {{ $root.connection.port }}
           resources: 
             limits:
               cpu: "500m" 
               memory: "500Mi" 
           env:
           {{- range $root.secret.keys }}
           - name: {{ . }}
             valueFrom:
               secretKeyRef:
                 name: {{ $secretName }}
                 key: {{ . }}
           {{- end}}
           readinessProbe:
            {{ $root.readiness.method }}
             path: {{ $root.readiness.path }}
             port: {{ $root.connection.port }}
            periodSeconds: {{ $root.readiness.periodSeconds}}
            initialDelaySeconds: {{ $root.readiness.initialDelaySeconds }}
            failureThreshold: {{ $root.readiness.failureThreshold }}
         hostAliases:
          - ip: {{ .Values.iam.ip }}
            hostnames:
            - {{ .Values.iam.hostname }}

---

apiVersion: v1
kind: Service
metadata:
  {{ if ne .Release.Namespace "temp" }}
  name: {{ $root.svcName }}
  {{ else }}
  name: temp-svc
  {{ end }}
spec:
  selector:
    app: {{ $root.appName}}
  ports:
    - protocol: {{ $root.connection.protocol }}
      port: {{ $root.connection.port }}
      targetPort: {{ $root.connection.port }}

